### PR TITLE
Use parametrized varchar type

### PR DESCRIPTION
**Pull request by losipiuk**
@electrum please take a look. This is preparatory work to expose parameterized VARCHAR(x) columns from Presto TPC-H connector.

### CODE REVIEW

**Comment by dain** [comment]
Looks like there are build errors in Travis

**Comment by losipiuk** [comment]
It failed because airlift-tpch uses java 7 and used java.util.Optional and compiled with jdk 8.
I changed it to use guava's Optional. But maybe it is better to bump java release version. Is there a reason to keep it at 7?

**Comment by losipiuk** [comment]
Draft of PR which makes use of this one in presto is here: https://github.com/prestodb/presto/pull/5012.
I will update it to use proper (non-snapshot) version of airlift-tpch as soon as it is released.

**Comment by martint** [comment]
No, we should just move it to Java 8. The Travis job is probably just misconfigured.

**Comment by losipiuk** [comment]
New version which bumps java in pom.xml and .travis.yml to 1.8 and is based on java.util.Optional.

**Pull request merged**
